### PR TITLE
CSS, favicon and Gpa converter added, Javascript separated, Handheld devices supported, output alerts fixed

### PR DESCRIPTION
**Pull request by Abhi-Kmr2046**
CSS and favicon added, Javascript separated

### CODE REVIEW

**Comment by shruti170901** [comment]
Very nice job @Abhi-Kmr2046! Basically all the things that were expected. Try changing the colour scheme once. You can also change the heading style

**Comment by Abhi-Kmr2046** [comment]
Any suggestion, what can I do to improve it overall?

**Comment by shruti170901** [comment]
Resolve conflicts and we will merge it

**Comment by shruti170901** [comment]
> Any suggestion, what can I do to improve it overall?

It is ready to be merged

**Comment by shruti170901** [comment]
@Abhi-Kmr2046 resolve conflicts

**Comment by Abhi-Kmr2046** [comment]
> 
> 
> @Abhi-Kmr2046 resolve conflicts

I have resolved the conflicts. You may check.

**Pull request merged**
