### PR TITLE
image folder and favicon added

### PR DESCRIPTION
**Pull request by astroidworld**
I have added a **favicon** to this website. I have added an Image folder and a favicon to this project.

### CODE REVIEW

**Comment by shruti170901** [comment]
Hey @astroidworld, We had a look at your favicon. You have written the initials Cc, in it. Can you try writing CG instead. I guess that will make more sense

**Comment by astroidworld** [comment]
yes, sure.

**Comment by astroidworld** [comment]
please can you assign this work to me?

**Comment by astroidworld** [comment]
please check it and merge it. Now I have made CG favicon.

**Pull request merged**
