### PR TITLE
Seperated js file from html and also added a basic css stylesheet

### PR DESCRIPTION
**Pull request by Palak-coder626**
Hey there! I'm Palak Jain. And I have contributed to your project by seperating the js file and I have added comments to it to make it more readable as well as refracted the code.. and I have also added styles.css file.

### CODE REVIEW

**Comment by Palak-coder626** [comment]
cgpa
Here is the final look of the website...

**Comment by Palak-coder626** [comment]
Pls consider my pull request and let me know if it's worth merging or not 🙂
@shruti170901 , @sriharikareddy2

**Comment by sriharikareddy2** [comment]
@Palak-coder626 we are looking into every pull request and we appreciate your work. Don't worry your pull request will be merged before mid evals. We are just waiting to avoid conflicts in the code

**Comment by Palak-coder626** [comment]
Thanks for your response!

**Pull request merged**
