### PR TITLE
NUMBER OF SUBJECTS IS VARIABLE NOW!

### PR DESCRIPTION
**Pull request by SihotiyaKartik**

### CODE REVIEW

**Comment by shruti170901** [comment]
@Kartik-NITP very nice effort! Try styling the boxes and try some alternate fonts for the top input box

**Comment by shruti170901** [comment]
Great going till now. Just one more thing. Look at these for motivation:
1. https://whatslot.metakgp.org/ (specially the dark mode part how the colour changes every time)
2. https://gyft.metakgp.org/ (specially the hover part)
So we can look at those as some things we would like to have.

**Comment by shruti170901** [comment]
Resolve conflicts and we will merge this

**Comment by shruti170901** [comment]
This is going to be the last merge so link the 4 point gpa page to the main page as well

**Comment by shruti170901** [comment]
index.html is still conflicting

**Comment by shruti170901** [comment]
wait i will rename the existing index.html

**Comment by SihotiyaKartik** [comment]
I have renamed my index.html file  to index4.html but still it is showing index.html as conflicting file and on clicking resolve conflicts, nothing happens

**Pull request merged**
